Rook bishop queen moves gens and moves generator piece board re updated
CSC207-2022F-UofT/course-project-chmess pull request #53
Opened 2022-12-02 23:13 UTC by Gursach44

2022-12-02 23:17 UTC, Gursach44 commented on src/main/java/engine/movegen/KnightMovesGen.java
> -
whoops sorry don't know why this is here, didn't mean to commit (don't even remember opening the file). But I don't think it's an issue anyways so whatever.

2022-12-03 04:43 UTC, cherche commented on src/main/java/engine/entities/Board.java
> +        piece.setCoords(x, y);
Not sure about this. I think the action of moving a piece should be abstracted elsewhere. The action of moving a piece (removing it from its old position, replacing it at the new position, then updating its coordinates) is comprised of three disparate parts. Directly calling piece.setCoords() requires us to know about the implementation of piece, while keeping the code elsewhere allows for looser coupling

2022-12-03 04:47 UTC, cherche commented on src/main/java/engine/movegen/MovesGenerator.java
> +                if(checkTile(toAdd, board)){
`checkTile` is an unclear name for this method.

2022-12-03 04:49 UTC, cherche commented on src/main/java/engine/movegen/MovesGenerator.java
> +                else{break;}
Code style makes this difficult to read. Preferred convention in Java is usually

```java
if {
...
} else if {
...
} else {
...
}
```
However, we have not discussed and will not have the time to discuss style.

2022-12-03 04:50 UTC, cherche commented on src/main/java/engine/movegen/MovesGenerator.java
> +            for(int distance = 1; distance < Board.WIDTH; distance++){
A while loop seems more natural. It might help avoid use of `break;` so that it is easier to trace code

2022-12-03 04:51 UTC, cherche approved these changes

2022-12-03 04:53 UTC, cherche commented
Somewhere, one of your changes has caused previously passing tests to fail.

2022-12-03 04:54 UTC, cherche requested changes
Please ensure that tests pass.

2022-12-04 01:18 UTC, cherche approved these changes

2022-12-04 02:56 UTC, cjwssb687 approved these changes

2022-12-04 21:10 UTC, adirao-projects approved these changes
Generally, all requested changes have been implemented. No major issues seen from my end. Minor issues with code style that Ryan pointed out. Great comments and code description!

2022-12-04 21:13 UTC, merged