Demo2 fix bugs
CSC207-2022F-UofT/course-project-chmess pull request #59
Opened 2022-12-07 07:31 UTC by cjwssb687

Fixed many bugs. There are still some issues being fixed.

2022-12-08 06:16 UTC, cherche requested changes
Looks fantastic. Works as expected and all tests now pass.

Minor issues (worth addressing before we merge):
- need better input validation for moves (e.g., what happens if a player tries to undo the last move when there is no previous board?)
- should have more javadoc
- should document how to run the game in the README

Major issues that should be left for a future refactor (don't need to address before merging):
- Need more careful choice of access modifiers and packaging
- Need to better respect Clean Architecture and SOLID design principles. A major refactor is needed, possibly even a redesign with significant rewrite. The current dependency graph is wacky
- Still need to test more classes (but not many!)

2022-12-09 03:17 UTC, cherche approved these changes, later dismissed

2022-12-09 04:23 UTC, David9Nagy approved these changes, later dismissed

2022-12-09 05:06 UTC, cherche approved these changes, later dismissed

2022-12-09 05:24 UTC, merged